### ISSUE TITLE
[Consider] Adding input[type="range"] selector plugin

### ISSUE THREAD

**Issue by beefchimi** [Shopify/postcss-shopify#4]
Originally brought up here:

https://github.com/Shopify/polaris-react/pull/1391#discussion_r193527021

Curious what our thoughts are on reducing some of that RangeSlider CSS by adding the [Input Range plugin](https://github.com/jonathantneal/postcss-input-range) ?

cc/ @kaelig

**Comment by kaelig** [comment]
Is there a spec proposal for this syntax?

**Comment by beefchimi** [comment]
From what I can find, there is no proposed official CSS syntax for these types of shadow DOM selectors.

If there was one, I'd like to believe it would be exactly what the plugin uses 😝 , these look good to me:

```
::range-track
::range-thumb
::range-lower
::range-upper
```

**Comment by kaelig** [comment]
I generally have issues with using a non-standard syntax in authored CSS/Sass, in that case because it can create friction by adding compilation complexity for consumers of polaris-react’s Sass - could we recommend using a mixin instead?

Considering how little this is recurring, I feel like introducing a new, non-standard postcss plugin may not show a great ROI here.

**Comment by beefchimi** [comment]
@kaelig what are your thoughts on this:
https://github.com/Shopify/polaris-react/pull/1584/files#diff-1559083c2d25f53f7fc781f9d228456d

**Comment by kaelig** [comment]
That's great! Thanks for the ping 👍

**Comment by beefchimi** [comment]
Cool - I will close this issue. That mixin belongs in `polaris-react` if I'm not mistaken.

Cheers!
